server:
  port: 8082
spring-doc:
  pathsToMatch: /api/v1/**
  title: Spring Security JWT
  version: v1
  description: Tutorials for creating JWT
  url: http://www.norulshahlam.com/
  name: norulshahlam & Co
  email: norulshahlam@gmail.com
  license-name: License 30AP
  license-url: url
spring:
  application:
    name: permit-to-work
    description: Permit to work application
    profile: generic
  output:
    ansi:
      enabled: ALWAYS
    main:
      banner-mode: off
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
jwt:
  secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # a day
  refresh-token:
    expiration: 604800000 # 7 days